#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

package: spec
output: openapi.gen.go
generate:
  models: false
  echo-server: false
  embedded-spec: true
import-mapping:
  ./common.yaml: github.com/trustbloc/vcs/pkg/restapi/v1/common
