#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "vcs interop test ci"

env:
  GO_VERSION: 1.18

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  Interop:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run BDD interop tests
        run: |
          echo $PATH
          go env
          echo ${{ github.workspace }}
          make bdd-interop-test
